//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.08.26 at 01:26:47 PM UTC 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://uri.etsi.org/02918/v1.2.1#", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package no.dfo.peppol.outbound.asicmanifestreader;