package no.dfo.peppol.outbound.asicmanifestreader;

//
//This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
//See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
//Any modifications to this file will be lost upon recompilation of the source schema. 
//Generated on: 2024.07.02 at 12:05:27 PM CEST 
//



import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
* <p>Java class for SigReferenceType complex type.
* 
* <p>The following schema fragment specifies the expected content contained within this class.
* 
* <pre>
* &lt;complexType name="SigReferenceType">
*   &lt;complexContent>
*     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
*       &lt;attribute name="URI" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
*       &lt;attribute name="MimeType" type="{http://www.w3.org/2001/XMLSchema}string" />
*     &lt;/restriction>
*   &lt;/complexContent>
* &lt;/complexType>
* </pre>
* 
* 
*/
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SigReferenceType")
public class SigReferenceType {

 @XmlAttribute(name = "URI", required = true)
 @XmlSchemaType(name = "anyURI")
 protected String uri;
 @XmlAttribute(name = "MimeType")
 protected String mimeType;

 /**
  * Gets the value of the uri property.
  * 
  * @return
  *     possible object is
  *     {@link String }
  *     
  */
 public String getURI() {
     return uri;
 }

 /**
  * Sets the value of the uri property.
  * 
  * @param value
  *     allowed object is
  *     {@link String }
  *     
  */
 public void setURI(String value) {
     this.uri = value;
 }

 /**
  * Gets the value of the mimeType property.
  * 
  * @return
  *     possible object is
  *     {@link String }
  *     
  */
 public String getMimeType() {
     return mimeType;
 }

 /**
  * Sets the value of the mimeType property.
  * 
  * @param value
  *     allowed object is
  *     {@link String }
  *     
  */
 public void setMimeType(String value) {
     this.mimeType = value;
 }

}
